In [ ]:
import pandas as pd

### 文件读写

In [3]:
# csv文件读写
df = pd.read_csv('sample_data.csv', sep=',')
df.to_csv('output.csv', index=False)

In [ ]:
# excel文件读写
df = pd.read_excel('sample_data.xlsx')
df.to_excel('output.xlsx')

### 创建 Sries

In [6]:
# 从列表创建 Series
s1 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
s1

a    10
b    20
c    30
d    40
dtype: int64

In [7]:
# 从字典创建
s2 = pd.Series({'a': 10, 'b': 20, 'c': 30, 'd': 40})
s2

a    10
b    20
c    30
d    40
dtype: int64

In [8]:
# 尝试访问
print("s1['a']:", s1['a'])
print("s2['b']:", s2['b'])

s1['a']: 10
s2['b']: 20

### 创建DataFrame

In [9]:
# 从二维列表创建 DataFrame
data1 = [
    [1, 'Alice', 24, 'New York'],
    [2, 'Bob', 27, 'Los Angeles'],
    [3, 'Charlie', 22, 'Chicago'],
    [4, 'David', 3, 'Houston']
]

df1 = pd.DataFrame(data1, columns=['ID', 'Name', 'Age', 'City'])	# 不指定columns默认为从0递增的序列
df1

   ID     Name  Age         City
0   1    Alice   24     New York
1   2      Bob   27  Los Angeles
2   3  Charlie   22      Chicago
3   4    David    3      Houston

In [10]:
# 从字典创建 DataFrame
data2 = {
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}

df2 = pd.DataFrame(data2)
df2

   ID     Name  Age         City
0   1    Alice   24     New York
1   2      Bob   27  Los Angeles
2   3  Charlie   22      Chicago
3   4    David   32      Houston

In [11]:
# 尝试访问
print("df1['ID']:", df1['ID'])
print("df2['Name'][1]:", df2['Name'][1])

df1['ID']: 0    1
1    2
2    3
3    4
Name: ID, dtype: int64
df2['Name'][1]: Bob